#pragma once

using namespace ATL;

template <class T>
class CProxy_IReadCardEvents : public IConnectionPointImpl<T, &__uuidof(_IReadCardEvents), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
